### ISSUE TITLE
nifty/ニフティ/旧ドメインのURLの修正

### ISSUE THREAD

**Issue by ncmbadmin** [NIFCLOUD-mbaas/MonacaFormApp#3]
以下のファイルはnifty/ニフティ/旧ドメインのURLがまだ残っているため、修正する必要があります。
https://github.com/NIFCLOUD-mbaas/MonacaFormApp/blob/gh-pages/DOCUMENT.md

**Comment by natsumo** [comment]
#5 にて対応完了
